---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - configure-server

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    # TYPEORM_HOST:
    # TYPEORM_PORT:
    # TYPEORM_USERNAME:
    # TYPEORM_PASSWORD:
    # TYPEORM_DATABASE:
