---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: nvm
  become: yes
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  args:
    creates: "~/.nvm/nvm.sh"

- name: nvm use
  become: yes
  shell: source ~/.nvm/nvm.sh && nvm install 13.8.0
  args:
    executable: /bin/bash

- name: "install pm2"
  become: yes
  shell: >
    source ~/.nvm/nvm.sh && npm install -g pm2
  args:
    executable: /bin/bash
