---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: Copying the Directory's contents (sub directories/files)
  become: true
  copy:
    remote_src: true
    src: /home/circleci/project/backend/dist
    dest: .
    owner: apache
    group: apache
    mode: 0644

- name: Start pm2
  command: pm2 start main.js
