---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: Copying the Directory's contents (sub directories/files)
  become: true
  copy:
    src: /tmp/dist/
    dest: .

- name: Start pm2
  command: pm2 start main.js
