---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: Copying the Directory's contents (sub directories/files)
  become: true
  copy:
    src: /root/project/backend/
    dest: .

- name: install modules
  become: yes
  shell: >
    source ~/.nvm/nvm.sh
    npm install
  args:
    executable: /bin/bash
    creates: ~/node_modules

- name: install modules
  become: yes
  shell: >
    source ~/.nvm/nvm.sh
    npm build
  args:
    executable: /bin/bash
    creates: ~/dist

- name: Start pm2
  become: yes
  shell: >
    source ~/.nvm/nvm.sh
    pm2 start dist/main.js
  args:
    executable: /bin/bash
