---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: Copying the Directory's contents (sub directories/files)
  become: true
  copy:
    src: /root/project/backend/
    dest: .

- name: install project
  shell: |
    source ~/.nvm/nvm.sh
    npm install
  args:
    executable: /bin/bash

- name: build
  shell: |
    source ~/.nvm/nvm.sh
    npm run build
  args:
    executable: /bin/bash

- name: copy .env
  shell: >
    cp ~/.env.sample ~/dist/.env
  args:
    creates: "~/dist/.env"

- name: Start pm2
  shell: |
    source ~/.nvm/nvm.sh
    cd dist
    pm2 start main.js
  args:
    executable: /bin/bash
