---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: Copying the Directory's contents (sub directories/files)
  become: true
  copy:
    src: /tmp/dist/
    dest: ./dist/

- name: Copying the Directory's modules (sub directories/files)
  become: true
  no_output_timeout: 1200
  copy:
    src: /tmp/node_modules_cache/
    dest: ./node_modules/

- name: Start pm2
  become: yes
  shell: source ~/.nvm/nvm.sh && pm2 start main.js
  args:
    executable: /bin/bash
